spring:
  profiles:
    active: sharding-tables
#    active: sharding-tables
#    active: sharding-tables
#    active: sharding-tables

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.quan.shardingjdbcdemo.shardingjdbc.entity

logging:
  level:
    org.springframework: info
  config: classpath:log/logback-dev.xml
server:
  port: 8080

